name: Greeting on a variable day

on: workflow_dispatch

env:
  DAY_OF_WEEK: Monday ## Environment variable for the entire workflow

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello ## Environment variable for the job
    steps:
      - name: "Say Hello Mona its Monday
        run: echo  . Today is !
        env:
          First_Name: Mona ## Environment variable only for the step Say Hello Mona its Monday" of the job "greeting_job"
